version: "3.8"

services:
  web:
    image: zangeets/symfony-backend:latest  # Utilisation de l'image du Docker Hub
    volumes:
      - ./symfony-backend:/var/www/symfony
    working_dir: /var/www/symfony
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - database
    environment:
      DATABASE_URL: "pgsql://root:root@database:5432/dockerProject"
    ports:
      - "8000:8000"
    networks:
      - app-network

  database:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dockerProject
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network

  react-app:
    image: zangeets/react-frontend:latest  # Utilisation de l'image du Docker Hub
    ports:
      - "3000:3000"
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  pg_data: {}

networks:
  app-network:
    driver: bridge
